/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function sweepy(root: string, entries: Array<string>): SweepyResult

export interface SweepyResult {
  reachableFiles: Array<string>
  unusedExports: Array<UnusedExport>
}

export interface UnusedExport {
  file: string
  name: string
}
